on: [push]
name: Unit test
jobs:
  test:
    runs-on: [ windows-latest ]
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.7', '3.1' ]
    name: Test on Windows Server with Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        run: ridk exec bundle install
      - name: Run tests
        run: bundle exec rake test
      - name: Build for distribution
        run: bundle exec gem build
      - name: Upload gem
        uses: actions/upload-artifact@v2
        with:
          name: fluent-plugin-widows-exporter
          path: |
            *.gem
